spring:
  liquibase:
    change-log: db/changelog-test.xml
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

